### ISSUE TITLE
go-ipfs/js-ipfs/js-ipfs-api unit and integration tests

### ISSUE THREAD

**Issue by victorb** [ipfs-inactive/dev-team-enablement#77]
_From @VictorBjelkholm on January 29, 2017 14:6_

# Acceptance Criteria

* [ ] When new commit happens in repository, jenkins should run the necessary tests and report back status to Github
* [ ] You should be able to trigger builds with specific versions of go-ipfs/js-ipfs-api to be able to test compatibility
* [x] JavaScript tests should be able to run in a browser 

# Tasks

- [x] Artifacts/Pipelines flow
- [x] JS side should be able to handle browser tests
    - [x] firefox/chrome installed on build-nodes (xvfb)
    - [x] Suitable adapters
- [ ] js-ipfs-api be able to use artifact from go-ipfs builds
- [ ] go-ipfs should be able to use artifacts from js-ipfs-api
- [x] Run tests on commit to repository
    - [x] Set build status on commit
- [x] Run tests on PR created/updated
    - [x] Set build status on PR

# Dependencies

Depends on #1

_Copied from original issue: ipfs/jenkins#4_

**Comment by VictorBjelkholm** [comment]
I'll start with adding `js-ipfs` unit tests from here.

**Comment by VictorBjelkholm** [comment]
_From @Kubuxu on February 4, 2017 18:39_

I think I am almost done with go-ipfs unit and sharness tests. Coverage is still pending.
